spring:
  datasource:
    url: jdbc:mysql://localhost/dept-2pm
    username: root
    password: techno
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 9001
  servlet:
    context-path: /department
